### ISSUE TITLE
Install on PS 1.6.1.1 full of errors

### ISSUE THREAD

**Issue by bbbenji** [jdanthinne/advancedfeaturesvalues#10]
After installing and setting multiple features on a product, every category and product page spits out the following error:
https://gist.githubusercontent.com/bbbenji/2d586823866ec0cc9e96/raw/5bc69cd36558b8e4edffcf9cecaf91d420931d3d/gistfile1.txt

After reverting the features to a pre install state, disabling, uninstalling the plugin and clearing cache, the frontend resumes but now in the backend once opening the "Features" tab the following error pops up:
https://gist.githubusercontent.com/bbbenji/5f177098a60d7ed7c0c0/raw/e0bdb0bbec9477b07696b91f3b016fcf457442b5/gistfile1.txt

Which roughly translates to: Error 500, server error. A problem occurred while loading tabs: some tabs may not be available. Try refreshing the page or check server logs.

Server log contains this:
https://gist.githubusercontent.com/bbbenji/5a92076575850de1d865/raw/e5fdbd92962a0b87d3d486046375e61243381ccc/gistfile1.txt

Renaming the file override/classes/FeatureValue.php fixes the problem. I think the uninstall is dirty.

**Comment by maritos** [comment]
classes/product.php
line 58:
            Db::getInstance(_PS_USE_SQL_SLAVE_)->executeS('SET @@group_concat_max_len = 4096');

should be:
            Db::getInstance(_PS_USE_SQL_SLAVE_)->execute('SET @@group_concat_max_len = 4096');

execute ! not executeS

**Comment by jdanthinne** [comment]
Thanks maritos! Fixed.
