### ISSUE TITLE
Installation process

### ISSUE THREAD

**Issue by pwajma** [jdanthinne/advancedfeaturesvalues#11]
Hello,

I am new on github and prestashop so sorry if I am asking obvious question.
I am on PrestaShop 1.6.0.14 
PHP 5.5.23 
I have downloaded .zip file to my computer and then from presta backend -> Modules -> add new module I upoaded it to my system. I received green message that module was uploaded...
And what now? I thought it will appear on module list and I will be able to install it - but I can not find it there.
I have also unzipped and uploaded it to /modules folder using ftp but I do not see and effect.

How I should install it properly?

Regards,
Andrzej

**Comment by bbbenji** [comment]
Make sure that your filters are set to `Installed & Not Installed` and `Enabled & Disabled`. Once you find the module there, install it. If it still does not show up, check the directory `modules/` to see if it's there, if not, manually unarchive the .zip to that location.

**Comment by jdanthinne** [comment]
Be sure to remove the -master suffix after downloading the archive from Github.

**Comment by pwajma** [comment]
Hi!
I removed suffix uploaded again using ftp and now is fine.
Thanks a lot!
ak
