### ISSUE TITLE
Can't see the module on the back-office (PS1.6.1.1)

### ISSUE THREAD

**Issue by XaviAlsina** [jdanthinne/advancedfeaturesvalues#13]
Hello, 

After downloading your plugin today, I tried to install it in my site (Prestashop 1.6.1.1), but I can't see the module on the back-office.

I've tried uploading it via back-office and also dragging the files on the /modules folder, with no luck.

If it helps, I am working with PHP Version 5.5.6.

PS: I can't even filter by author, so it seems that somehow there must be something missing.

**Comment by bbbenji** [comment]
Have you checked the similar issue here?

https://github.com/jdanthinne/advancedfeaturesvalues/issues/11

**Comment by XaviAlsina** [comment]
My bad for do not check the issue. Thanks!
