### ISSUE TITLE
Compatibility issue with pretashop 1.5.4.1

### ISSUE THREAD

**Issue by kartikjh** [jdanthinne/advancedfeaturesvalues#15]
I am triying to install on prestashop 1.5.4.1 and it gives error given below can you please make it compatible with pretashop 1.5.4.1

The following module(s) were not installed properly:

```
- advancedfeaturesvalues :
The version of your module is not compliant with your PrestaShop version.
```

**Comment by jdanthinne** [comment]
Unfortunatly, the module needs features only available in more recent versions... You should try to update your installation first. 1.5.4.1 is more than two years old.
