### ISSUE TITLE
BlockLaxeredNavigation wrong filter

### ISSUE THREAD

**Issue by Nermendis** [jdanthinne/advancedfeaturesvalues#18]
I set the compositions -> Elastane filter. This filter contain one product, the second (ineo...).
The filter doesn't disappear the first product (Printed Dress).

![advancedfeatures4](https://cloud.githubusercontent.com/assets/8681770/11242756/f98ecebc-8e03-11e5-8e24-6ee053d4511d.PNG)

**Comment by jdanthinne** [comment]
Why should it disappear? Its composition is Cotton and Cotton is selected in the filters (which are not exclusive). Printed Dress should disappear if you uncheck Cotton.
