### ISSUE TITLE
Uninstall error

### ISSUE THREAD

**Issue by MaartenBerkvens** [jdanthinne/advancedfeaturesvalues#2]
Hello,

How to uninstall this module manually?
I installed the module then I saw the PHP <5.5 issue. I have PHP 5.3.29
Productfunctions is not working at all anymore :(
Now I can't uninstall the module. I'm getting an error:

[PrestaShop] Fatal error in module Module:
Uncaught exception 'ReflectionException' with message 'Class FeatureValueOverrideOriginal_remove550ad38a02e19 does not exist' in /home/berkve21/domains/baby-schoenen.nl/public_html/shop/classes/module/Module.php:2496 Stack trace: #0 /home/berkve21/domains/baby-schoenen.nl/public_html/shop/classes/module/Module.php(2496): ReflectionClass->__construct('FeatureValueOve...') #1 /home/berkve21/domains/baby-schoenen.nl/public_html/shop/classes/module/Module.php(2405): ModuleCore->removeOverride('FeatureValue') #2 /home/berkve21/domains/baby-schoenen.nl/public_html/shop/classes/module/Module.php(592): ModuleCore->uninstallOverrides() #3 /home/berkve21/domains/baby-schoenen.nl/public_html/shop/modules/advancedfeaturesvalues/advancedfeaturesvalues.php(84): ModuleCore->uninstall() #4 /home/berkve21/domains/baby-schoenen.nl/public_html/shop/controllers/admin/AdminModulesController.php(805): AdvancedFeaturesValues->uninstall() #5 /home/berkve21/domains/baby-schoenen.nl/public_html/shop/controllers/admin/AdminModulesContr

**Comment by jdanthinne** [comment]
Have you tried removing manually the module folder? You have to remove also the overrides (/override/classes/FeatureValue.php, /override/classes/Product.php, /override/controllers/admin/AdminFeaturesController.php, /override/controllers/admin/AdminProductsController.php, /override/modules/blocklayered/blocklayered.php)

**Comment by MaartenBerkvens** [comment]
Yes...it worked..

any chance to make this work on older PHP versions ?
It’s a great module!

**Comment by jdanthinne** [comment]
I'm still searching the cause for this bug on older versions. And still don't know if it's a bug on my side, or on the Prestashop installation process…

**Comment by MaartenBerkvens** [comment]
I also get a syntaxerror:

Parse error: syntax error, unexpected '=', expecting ')' in /home/berkve21/domains/baby-schoenen.nl/public_html/shop/override/controllers/admin/AdminFeaturesController.php on line 85

**Comment by jdanthinne** [comment]
Can you copy the code from this particular line? Overridden files are made of different part from different modules…

**Comment by MaartenBerkvens** [comment]
The line is:

if (empty($positions = Tools::getValue($table)))

**Comment by jdanthinne** [comment]
Can you try changing that like I just did: https://github.com/jdanthinne/advancedfeaturesvalues/commit/f1d4e82347b6aeff561e7af8c5511d91d3950fa1

**Comment by MaartenBerkvens** [comment]
Yes, that worked !
Seems that everything is working now even on PHP 5.3
I only had to copy de overide/modules/ manually. The prestashop installation did not do that.

----Origineel Bericht----
Van : notifications@github.com
Datum : 20/03/2015 09:35
Aan : advancedfeaturesvalues@noreply.github.com
Cc : maartenberkvens@kpnplanet.nl
Onderwerp : Re: [advancedfeaturesvalues] Uninstall error (#2)
Can you try changing that like I just did: f1d4e82

**Comment by jdanthinne** [comment]
Great news. For the manual copy, which version of PS are you using? Modules overrides is a new function (PS 1.6.0.11+)

**Comment by MaartenBerkvens** [comment]
I'm using 1.6.0.9 so that explains it maybe :)
----Origineel Bericht----
Van : notifications@github.com
Datum : 20/03/2015 14:04
Aan : advancedfeaturesvalues@noreply.github.com
Cc : maartenberkvens@kpnplanet.nl
Onderwerp : Re: [advancedfeaturesvalues] Uninstall error (#2)
Great news. For the manual copy, which version of PS are you using? Modules overrides is a new function (PS 1.6.0.11+)

**Comment by jdanthinne** [comment]
Yes, but this particular file is only a bonus for the correct ordering of the features values in the blocklayered filters. People could survive that :-)
