### ISSUE TITLE
Impossible to see your module in the backend

### ISSUE THREAD

**Issue by VincentPau** [jdanthinne/advancedfeaturesvalues#22]
Hello

First of all thank you to share your work
My problem is that I can not aciver the module because I do not see it in the admin
I tried :
1 to install via "add a new module" in admin
presta told me that the module has been downloaded, but it is invisible
2 via FTP but again nothing in the admin modules

I'm presta 1.6.1.1
with the basic theme

I'm stuck and did not see how to move forward
It is the only module found, that allows to choose multiple attributes of a product at the same time
What is a native function on Magento by the way
I will appreciate very much a helping hand

Thank you very much in advance

Vince

**Comment by jdanthinne** [comment]
See https://github.com/jdanthinne/advancedfeaturesvalues/issues/11

**Comment by VincentPau** [comment]
Thank you so much
But now 
http://ffitness.fr.vahns.com/fr/kettlebells-pour-salle-de-sport/1271-kettlebell-.html
I'd would like to select 4 different attribut together
eg
4 kg + 8kg + 12 kg
Can your module do it?
if yes
je ne suis même plus sur que votre module sert bien à sélectionner plusieurs atributs à la fois sur une fiche produit pour les envoyer tous dans le panier
Qu'est ce que j'ai raté?
merci de votre support
Vincent

**Comment by jdanthinne** [comment]
In fact, I think you're talking about attributes (what this modules doesn't handle), not features (what this modules handles)…

**Comment by VincentPau** [comment]
Ok 
Sorry to disturb you
By the way do you know a module which can solve my probem?
Thank you

**Comment by jdanthinne** [comment]
Sorry, but no idea… I haven't used Prestashop for a while now. Have you tried the Prestashop Addons Marketplace? http://addons.prestashop.com/fr/

**Comment by VincentPau** [comment]
yes but ...
Thank you
