### ISSUE TITLE
Change the ',' Separator 

### ISSUE THREAD

**Issue by erfanmhd** [jdanthinne/advancedfeaturesvalues#23]
hi, 
i was wondering how can i change the comma separator? 
i want every feature value to be on a new line, i guess if i change the separator from "," to "<br>" i could do that. 

can you give me a hint ?

**Comment by jdanthinne** [comment]
In override/classes/Product.php, search for SEPARATOR.

**Comment by erfanmhd** [comment]
Hi jdanthinne, 
thanks for reply, i've found this line product.php  near line 53 and 69 and replaced the  ", " with "_" but nothing happens at my frontend. 
i'm still gerring commas as separator. 

<code>SELECT `name`, GROUP_CONCAT(value ORDER BY `fv`.`position` SEPARATOR "_") AS `value`, `pf`.`id_feature`</code>

**Comment by jdanthinne** [comment]
Did you change the file in the /modules/advancedfeaturesvalues/override/ or in /override/ directly? The second option is the good one. And you should use "<br>" instead of "_" I think.

**Comment by erfanmhd** [comment]
ive changed the file from /modules/advancedfeaturesvalues/override/ 
it doesn't matter what i put in there az separator < br >  or - it doesn't changes the commas !

**Comment by jdanthinne** [comment]
In fact, Prestashop copy the module's override folder into the root /override folder of your server. You should change the files in this particular folder in order to make it work for you.

**Comment by toyoted** [comment]
I see modification made in override in my front office BUT i would like to make a new line for each feature but the "`<br>`" separator doesn't work properly (In front office it writes "`<br>`" instead of a new line)

> `SELECT name, GROUP_CONCAT(value ORDER BY fv.position SEPARATOR "<br>") AS value, pf.id_feature`
