### ISSUE TITLE
csv import

### ISSUE THREAD

**Issue by akafester** [jdanthinne/advancedfeaturesvalues#3]
I have installed this excellent module to solve a problem that shouldn't exist. So for that, thanks for the great work.
I'm seeking the separator to use in the cvs importer. I have tried with the pipes but it doesn't seem to work. Is there a way to do a multiple feature value import via the cvs importer? I'm using the latest 1.6 version.

**Comment by jdanthinne** [comment]
CVS import is not supported yet. In my todo list...

**Comment by jdanthinne** [comment]
I've never tested the import, but I've just had a quick look at the current code and I can see that features need to be formatted this way 
…;Name:Value:Position;…
Have you tried 
…;Name:Value1:Position,Name:Value2:Position,Name:Value3:Position;… ?

**Comment by akafester** [comment]
I have tried that way, but the problem is that i want it to be: ;Feature:Value1|Value2|Value3:Position,Feature:Value.......... then your module take over to make sure prestashop doesn't throw away the data.

I can see, on the same thread that i found your module, that someone posted a way to make the above work: https://www.prestashop.com/forums/topic/176242-modification-select-multiple-values-for-one-feature/page-10#entry1914984
Can this be incorporated to your module?

**Comment by jdanthinne** [comment]
So, do you mean that the way I suggested doesn't work, or that it doesn't suit your workflow?

**Comment by akafester** [comment]
I'm sorry, but i think i might misunderstood what you meant. 
The way prestashop wants input is: "feature:value:position:customize". This isn't really usable if I want to import af feature with multiple values, and then use the layered navigation to filter. 
So if I, for example, had a shirt in my shop with two compositions of fabric then i could write it like so: 
"Fabric:cotton / silk:0:0".
In this way i can't make filter the fabric by silk alone because prestashop saves it as "cotton / silk", witch makes it impossible to search for silk alone. 
You then recommended that I used "feature:value1:position:customize;feature:value2:position:customize"
Witch then would be:
"Fabric:cotton:1:0;Fabric:Silk:2:0". Is this correctly understood? Will try it tomorrow regardless but just to make sure :).

**Comment by jdanthinne** [comment]
Yes, "Fabric:cotton:1:0;Fabric:Silk:2:0" seems what Prestashop expect… But try and tell me, I've never used import.

**Comment by akafester** [comment]
It works flawlessly. I tried with a couple of test produkts and it seems that prestashop doesn't care about the position value.
For example: 
Something:Yes:0;Fabric:Cotton:1;Fabric:Silk:2;Something:No:3
And
Something:Yes:0;Fabric:Cotton:1;Fabric:Silk:1;Something:No:2
have the exact same result. No errors and both products have the correct input selected.
Thank you very much for your help :).
