### ISSUE TITLE
Module is ThirtyBees compatible - perhaps donate to ThirtyBees project?

### ISSUE THREAD

**Issue by Acer-ZA** [jdanthinne/advancedfeaturesvalues#31]
Hi Jérôme

I haven't seen any contact info for you, so I thought I'd make a post here. Hopefully, you see it.
I've been looking for a decent "multiple values for a feature" module for ThirtyBees (PS 1.6 fork) for a long time and I finally found yours. It's by far the best free one I've seen and it's even more awesome because it works with ThirtyBees! :) And it incorporates beautifully into the BlockLayered filter :)
Your module has great features and fills in an important feature gap in both PS 1.6 and ThirtyBees. I'd like to take say thank you as you've saved the day for me and my company because of this module :)

**That brings me to the suggestion I'd like to make:**
As it seems that you've completed development on this module and that work on it has stalled, can I perhaps make the very large request and suggestion to please donate your awesome module to the ThirtyBees project so that it can be incorporated into the core as a core feature?
It would bring great value to the OpenSource ThirtyBees project and community. They can then continue development and enhancement to your module from there.

Just a thought and suggestion. Kindly let me know your response.

My post on the ThirtyBees forum regarding your module:
https://forum.thirtybees.com/topic/3456-multiplefeatures/?tab=comments#comment-30387

**Comment by jdanthinne** [comment]
Hey!
As you've seen, I'm not into PS anymore, and working on update and compatibility is not possible for me…
I'd be very happy to donate this to your project.

**Comment by Acer-ZA** [comment]
Hi Jérôme

Thanks so much for your quick reply and your awesome response!
Can I please suggest that you reach out and get in touch with the ThirtyBees project owners as I'm not sure what the process is / what they require?

**I've created a thread on the ThirtyBees forum for this topic:**
https://forum.thirtybees.com/topic/3472-multiple-values-for-a-feature-module-module-creator-would-like-to-donate-the-module-to-tb-can-tb-project-owners-please-assist/

https://thirtybees.com

Please let me know how it goes!
Thanks again! :) :)
