### ISSUE TITLE
Character ammont display limit.

### ISSUE THREAD

**Issue by kpawel** [jdanthinne/advancedfeaturesvalues#8]
Hello, i use your module and it works fine.

But i have a little problem.
After adding many values to one feature in product page in table not all features are displayed.

Probably problem is some character limit, becouse i see that just text is cutted.
http://i.imgur.com/goeqSrJ.jpg

In back-office i checked and all features are fine.

**Comment by jdanthinne** [comment]
Closed as a duplicate of https://github.com/jdanthinne/advancedfeaturesvalues/issues/5.
